"""Add articles table

Revision ID: 3bd894e75aab
Revises: 0de8e09b92e5
Create Date: 2025-03-05 12:20:09.665881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bd894e75aab'
down_revision: Union[str, None] = '0de8e09b92e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'articles',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('url', sa.Text(), unique=True, nullable=False),
        sa.Column('stock_symbol', sa.String(), nullable=False),
        sa.Column('title', sa.Text(), nullable=True),
        sa.Column('author', sa.Text(), nullable=True),
        sa.Column('published_date', sa.String(), nullable=True),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('is_embedded', sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column('scraped_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
